version: '3.8'
services:
  web:
    build: ./alpca-consumer/
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./alpca-consumer:/app
    working_dir: /app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
