version: '3.8'

services:
  web:
    build: ./alpca-consumer/
    image: alpca-consumer:latest
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./alpca-consumer:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  celery:
    image: alpca-consumer:latest
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./alpca-consumer:/app
    working_dir: /app
    depends_on:
      - web
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  celerybeat:
    image: alpca-consumer:latest
    command: celery -A celery_app beat --loglevel=info --scheduler celery.beat.PersistentScheduler
    volumes:
      - ./alpca-consumer:/app
    working_dir: /app
    depends_on:
      - web
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  npm:
    image: dashboard:latest
    build: ./dashboard-react
    working_dir: /app
    depends_on:
      - web
    ports:
      - "80:3000"
    volumes:
      - ./dashboard-react:/app
