version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8000:8000"
      - "3000:3000"
    environment:
#      - SERVICES=serverless,s3,lambda,ec2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
